# 当main有代码提交或者有pr时，自动build gitbook，并覆盖git@github.com:zeromicro/go-zero.git仓库中内容
# 以实现自动发布文档

name: Document Build

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo pwd
        run: export wd=${PWD} && echo $wd
      - name: echo work dir
        run: echo ${wd}
      - name: checkout code
        uses: actions/checkout@v2
      - name: chmod contributor tool
        run: chmod +x ${wd}/.github/workflows/contributor-tool
      - name: get latest contributors(cn)
        run: ${wd}/.github/workflows/contributor-tool -f contributor -l zh -o ${wd}/go-zero.dev/cn/contributor.md
      - name: get latest contributors(en)
        run: ${wd}/.github/workflows/contributor-tool -f contributor -l en -o ${wd}/go-zero.dev/en/contributor.md
      - name: use node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.1'
      - name: install gitbook
        run: npm install gitbook-cli -g
      - name: gitbook version
        run: gitbook --version
      - name: gitbook install
        run: gitbook install
      - name: build
        run: cd ${wd}/go-zero.dev && gitbook build
      - name: delete original index
        run: rm -f ${wd}/go-zero.dev/_book/index.html
      - name: build index
        run: ${wd}/.github/workflows/contributor-tool -i  ${wd}/go-zero.dev/_book/index.html
      - name: chmod
        run: chmod +x ${wd}/.github/workflows/build.sh
      - name: publish
        run: ${wd}/.github/workflows/build.sh ${{ secrets.ACCESSTOKEN }}
        shell: bash
